[theme]
base = "dark"
primaryColor = "#68B7FF"
backgroundColor = "#070B14"
secondaryBackgroundColor = "#11192A"
textColor = "#F4F7FB"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
